["bin/z.sh"]
    type = "file"
    url = "https://raw.githubusercontent.com/rupa/z/refs/heads/master/z.sh"
    refreshPeriod = "168h"

[".vim/pack/plugins/start/nerdcommenter"]
    type = "git-repo"
    url = "https://github.com/preservim/nerdcommenter.git"
    refreshPeriod = "168h"

[".vim/pack/plugins/start/ctrlp"]
    type = "git-repo"
    url = "https://github.com/ctrlpvim/ctrlp.vim.git"
    refreshPeriod = "168h"
