# Change c-b as prefix to c-<space>
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# This is needed to allow programs to send OSC52 copy/paste commands, *without*
# needing to send a "DCS passthrough" to escape it for tmux. Before, this
# needed allow-passthrough, and support in the client for that.
set -s set-clipboard on
